use_frameworks!

platform :ios, '9.0'

target 'VersionEx_Example' do
  pod 'VersionEx', :path => '../'

  target 'VersionEx_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble', '~> 9.0.0'
  end
end
